apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilt-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tilt-demo
  template:
    metadata:
      labels:
        app: tilt-demo
    spec:
      containers:
      - name: tilt-demo
        image: tilt-demo:latest
        ports:
        - containerPort: 5000
